### ISSUE TITLE
Gateway does not register directly after restart

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3338] opened 2023-10-08 16:29 UTC
The sleep should be after the loop:

https://github.com/fedimint/fedimint/blob/cfee01603b7484aeed1aed87c45df810300b1f6d/gateway/ln-gateway/src/lib.rs#L989-L1000

**Comment by douglaz** [comment] 2023-10-27 18:54
Pretty much alive on v0.1

**Comment by elsirion** [comment] 2023-10-30 11:43
Any idea why? Does fetching route hints fail for you? [A version of the backported fix](https://github.com/elsirion/fedimint/commits/v0.1.1-patch-btcpp) worked for me (but I was using CLN, so maybe there are different issues?).

**Comment by justinmoon** [comment] 2023-10-30 16:20
Call: would be nice to have a local reproduction of this

**Comment by douglaz** [comment] 2023-10-30 16:25
Tested on production gateway. Procedure was like:
1) Restart a gateway that is already registered to a federation using LND
2) list-gateways on fedimint-cli will still show because it's cached
4) After some minutes list-gateways on fedimint-cli stops showing due to the old registration expiration
5) After some minutes (less than 10) the list-gateways will show again

**Comment by m1sterc001guy** [comment] 2024-02-15 17:01
The code for this has been changed so that all gateways are registered once the gateway configuration is set

```
loop {
                        if let Some(gateway_config) = gateway.get_gateway_configuration().await {
                            let gateway_state = gateway.state.read().await.clone();
                            if let GatewayState::Running { .. } = &gateway_state {
                                Self::register_all_federations(&gateway, &gateway_config).await;
                            } else {
                                // We need to retry more often if the gateway is not in the Running state
                                const NOT_RUNNING_RETRY: Duration = Duration::from_secs(10);
                                info!("Will not register federation yet because gateway still not in Running state. Current state: {gateway_state:?}. Will keep waiting, next retry in {NOT_RUNNING_RETRY:?}...");
                                sleep(NOT_RUNNING_RETRY).await;
                                continue;
                            }
                        } else {
                            warn!("Cannot register clients because gateway configuration is not set.");
                        }

                        // Allow a 15% buffer of the TTL before the re-registering gateway
                        // with the federations.
                        let registration_delay = GW_ANNOUNCEMENT_TTL.mul_f32(0.85);
                        sleep(registration_delay).await;
                    }
 ```

Should we close this?

**Comment by douglaz** [comment] 2024-02-15 21:49
We may have other issues related to registration but this particular one seems to be fixed.

**Closed by douglaz** 2024-02-15 21:49 UTC
Labels: bug, lightning
