### ISSUE TITLE
Faster dev environment setup

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#317] opened 2022-08-02 12:34 UTC
It's great that we support setting up a dev environment in 2 steps: install nix and run `tmuxinator.sh`. 

But the problem now it that it takes like 10+ minutes for `tmuxinator.sh` to run. Has to compile bitcoin core and lightningd. Is there any way we could just download binaries for these? Of course might want to build from source for deployments, but for development it's a huge friction point for prospective contributors.

**Comment by dpc** [comment] 2022-08-02 16:13
Unclear to me if you're already using Flakes (I see both flake.nix and custom shell.nix), so just in case: https://nixos.wiki/wiki/Flakes#Super_fast_nix-shell


I haven't set it up myself yet, so I'm not sure if it will work, but possibly you could cache the public build in cachix .https://scrive.github.io/nix-workshop/06-infrastructure/01-caching-nix.html

**Comment by justinmoon** [comment] 2022-08-02 17:04
We use `shell.nix`. We have a partial Flakes setup but it's not used aside from one CI task. It's not a good situation. The problem is that none of us really understand Nix.

**Comment by rndhouse** [comment] 2022-08-09 13:56
lilsus from discord wanted someone to double check how long the setup takes, so I had a go:

At commit https://github.com/fedimint/minimint/commit/83e16321ea6328b1691222f768873534ea666d3d I built a podman image using the root Dockerfile. I then ran the image as a podman container and executed `scripts/tmuxinator.sh` up until `source scripts/build.sh`. This basically executes Nix and Cargo from scratch.

The whole process took 56 mins on my machine.

**Comment by dpc** [comment] 2022-08-09 16:49
@rndhouse Are you aware what is taking the most time? 

Are you able to try #322 ? 

Even on the old setup (shell.nix) on my Linux laptop getting `nix shell` seemed to take couple of minutes. Do I understand correctly that building bitcoind from scratch with M1 compilation patches is at fault here?

**Comment by rndhouse** [comment] 2022-08-09 17:09
> @rndhouse Are you aware what is taking the most time?

From observing stdout, I would guess that compiling bitcoind took the most time and then secondly compiling minimint (rust dependency crates).

> Are you able to try #322 ? 

I'll give it a go!

**Comment by dpc** [comment] 2022-08-09 17:14
Well, in that case I don't think #322 is going to help much with the first time build. It's all because some patched build needs to be used for MacOS (or just MacOS M1) users. Adding these binaries to some cache will fix it.

**Comment by dpc** [comment] 2022-08-09 17:46
![Screenshot from 2022-08-09 10-43-30](https://user-images.githubusercontent.com/9209/183723433-d985f562-de66-4868-8b59-7b27b85cf1bd.png)


I see. I had to upgrade Nix which wiped my `/nix` and for starter we need to download 1.3G from Nix store with all the binaries. Existing users of Nix would have a lot of that stuff cached already.

**Comment by dpc** [comment] 2022-08-09 17:51
Now I'm wating for clightning to build (and this is not MacOS, so it must be happening all the time).

**Comment by dpc** [comment] 2022-08-09 18:12
OK. So I didn't notice bitcoind being built, so it's only the dev version of clightning for dev users.

**Comment by dpc** [comment] 2022-08-20 06:59
The fundamental price for having a reproducible dev environment is that every dev needs to download the exact same set of binaries that compose into this environment. This is one time cost - after that everything is cached and rarely changes. I don't think we can do all that much about this part.

Since we reverted to vanilla bitcoind, we get the binary built from NixOS, at least for Linuxes. From what I can tell: https://github.com/NixOS/nixpkgs/issues/95903#issuecomment-914061347 Mac users should also get prebuilt images.

So the last part is the clightning with `--enable-developer` which is kind of a custom thing. 

The best we could do is to point our users at the public cache we use in the CI to get as much as possible of this stuff prebuilt, I guess.

**Comment by dpc** [comment] 2022-08-20 07:07
TODO:

* [ ] after #406 lands add optional `nix-env -iA cachix -f https://cachix.org/api/v1/install` + `cachix use fedimint` step to the `dev-env.md`
* [ ] I doubt we're going to get a aarch64-darwin CI, so we can either try cross-compiling to populate cache (I'm pessimistic if this is doable) or have one of the trusted developers (@justinmoon) set up a cronjob or something to periodically build everything and push it to `cachix`

**Comment by dpc** [comment] 2022-09-26 23:36
Dev environment is quite OK. Closing. I'm tracking other work elsewhere.

**Closed by dpc** 2022-09-26 23:36 UTC

**Comment by justinmoon** [comment] 2022-09-27 01:12
Great work here @dpc! It's really improved drastically.
