### ISSUE TITLE
A command to deserialize and print debug output of a `Transaction` (and possibly other most common structures)

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1919] opened 2023-03-14 21:04 UTC
If I have a hex output from the CI, would be nice not to have to hack test code to see what's in there.

https://gist.github.com/elsirion/3afaf6da90cec6ccf0ee2457594b4441

In the link some code  that does the same thing.

**Comment by ngutech21** [comment] 2023-03-15 07:36
I would like to work on this issue. Where do I find more examples of these Transactions in the log? How can I reproduce them?

**Comment by ngutech21** [comment] 2023-03-19 08:43
This issue can be closed because branch got merged

**Closed** 2023-03-19 15:32 UTC
Labels: good first issue
