### ISSUE TITLE
Excessively long tmp directories cause devimint to fail

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3856] opened 2023-12-06 17:43 UTC
Sometimes when running `just mprocs` on a Mac I get this error:

```
00:00:30 Error: polling lightningd after 10 retries
00:00:32 Caused by:
00:00:32     0: connect to lightningd
00:00:32     1: path must be shorter than libc::sockaddr_un.sun_path
```

Relevant log from `devimint`:

```
00:00:11 2023-12-06T17:29:02.670629Z  INFO devimint: Test setup in "/var/folders/19/h_y32l8s1lxfrpxctd1673p00000gn/T/nix-shell.wNpTCB/devimint-90964"
```

The `/var/folders/19/h_y32l8s1lxfrpxctd1673p00000gn/T/` prefix is getting to thrown in by the operating system or something and nix is inheriting it.

Seems like there's some automated tmp file rotation scheme on mac: https://www.reddit.com/r/mac/comments/n69ezw/screenshots_going_to_a_temporary_items_folder_in/

**Comment by dpc** [comment] 2023-12-11 20:20
https://developer.apple.com/bug-reporting/ :laughing:

**Comment by bradleystachurski** [comment] 2023-12-21 14:58
I believe the root cause is socket paths that exceed a character limit (104 on mac, 108 on some linux distros). The mentioned issue :point_up: has more context but is a duplicate of this.

**Comment by dpc** [comment] 2023-12-21 18:24
We should detect paths being too long and print the warning/fail earlier. Otherwise not much we can do here.

Mac users could just set their `$TMP` to a different directory (`$(pwd)/target/tmp` maybe) or something. Not sure if we want to automate it for them, because cleaning it up will become a problem.

**Comment by Maan2003** [comment] 2023-12-21 19:38
Mac users can just install linux :stuck_out_tongue: 
https://asahilinux.org/fedora/#device-support

**Comment by bradleystachurski** [comment] 2023-12-21 23:08
Out of curiosity, can another linux user run

```
nix build .#ci.latencyTest -L
```

I'm on linux and get the same error `path must be shorter than libc::sockaddr_un.sun_path`.

Would we ever need to run a `nix build .#ci*` command locally?

**Comment by dpc** [comment] 2023-12-21 23:37
> Would we ever need to run a `nix build .#ci*` command locally?

We use `.#ci` in the CI all the time. `ci` prefix there enables `ci` cargo build profile which we optimized for CI (reasonably fast to compile, but also not terribly slow at running tests, etc.)

**Comment by dpc** [comment] 2023-12-22 03:44
> `nix build .#ci.latencyTest -L`

Passed on my system just fine, as it probably does multiple times a day in CI. :)

**Comment by dpc** [comment] 2023-12-22 03:45
If you hit issues, see if you can capture `mktemp --tmpdir -d fm-client-XXXX` from inside the script/shell you're experiencing problems.

**Comment by dpc** [comment] 2024-03-14 01:37
I hope. Reopen if not. :D

**Closed by dpc** 2024-03-14 01:37 UTC
