### ISSUE TITLE
`0.2.2` release binaries are incomplete 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4305] opened 2024-02-12 16:14 UTC
https://github.com/fedimint/fedimint/releases/tag/v0.2.2

* It's missing `fedimintd`, `fedimint-cli`, and `recoverytool`. 
* Also, what platforms do `gatewayd` and `gateway-cli` run on?

<img width="904" alt="image" src="https://github.com/fedimint/fedimint/assets/4335621/9678e119-f44c-49de-a746-ec265dd3db6b">

**Comment by justinmoon** [comment] 2024-02-12 17:51
Also, RPC and DEB are suspiciously small

**Comment by dpc** [comment] 2024-02-15 19:51
The build was failing and most stuff was not actually produced and e.g. client-pkgs does not contain any binaries, so that deb/rpm was empty. It should be fixed now.

As for signing, since binaries should be reproducible, we should write some `just sign-release` script that would build binaries from a given tag and sign them with pgp, which we could then ... donno ... upload somewhere, or paste on a wiki?

**Comment by justinmoon** [comment] 2024-02-15 23:42
Do we test reproducibility at all?

**Comment by dpc** [comment] 2024-02-16 03:20
I checked it manually a few times.

BTW. #4339

**Comment by dpc** [comment] 2024-07-24 06:41
Old and not relevant anymore. Improvements has been made.

**Closed by dpc** 2024-07-24 06:41 UTC
