### ISSUE TITLE
Config API: Split `ReadyForConfigGen` to 2 states

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2815] opened 2023-07-21 17:35 UTC
The `run_dkg` config API RPC method transitions state to `ReadyForConfigGen` and blocks until it succeeds or fails. Let's split these state into 2: `ReadyForConfigGen` and `RunningConfigGen`. 

`run_dkg` will transition to `RunningForConfigGen`, then spawn a task which actually runs DKG and transitions state according to success / failure as it does currently. The big change is doing this in a background task instead of blocking. Then the UI can just poll server status instead of waiting for a blocking command which might timeout or get disconnected.

`RunningConfigGen` state will hold a handle to that task which runs DKG. This gets dropped when we move to another state causing the DKG task to terminate.

**Comment by wbobeirne** [comment] 2023-09-07 16:19
Is this directly related to, or a duplicate of #2781? Should they be consolidated?

**Comment by justinmoon** [comment] 2023-09-11 14:15
I think they are duplicates

**Comment by bradleystachurski** [comment] 2023-09-17 00:09
Sanity check that I'm able to repro the root issue. I added a sleep in `distributed_gen` so the request will timeout and this is what shows in the UI. Does that correctly identify the issue?

![Screenshot 2023-09-16 at 6 06 56 PM](https://github.com/fedimint/fedimint/assets/11034691/c6aa342b-fde4-4353-8baa-8ceabc2db5de)

**Comment by bradleystachurski** [comment] 2023-09-17 00:56
@justinmoon I took a different approach for implementation, so please let me know if I'm missing context.

I didn't see the need to introduce `RunningConfigGen`. Keeping the existing states and returning once the new task is spawned resolved the above issue without any changes required in fedimint/UI.

**Comment by justinmoon** [comment] 2023-09-18 22:54
> I didn't see the need to introduce `RunningConfigGen`. Keeping the existing states and returning once the new task is spawned resolved the above issue without any changes required in fedimint/UI.

Clever! Yea I think that works.

**Closed** 2023-09-18 23:05 UTC
