### ISSUE TITLE
Client state machines can swallow panics

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2585] opened 2023-05-25 20:31 UTC
Me and @m1sterc001guy left `GatewayClientModule.input_amount()` and `GatewayClientModule.output_amount()` as `unimplemented!()` while working out the gateway client. We ran into a scenario where we were waiting for state machine to terminate, but it never did, and no logs or errors were printed even with `RUST_BACKTRACE=1`. After like 30 minutes of debugging we finally narrowed it do to these unimplemented methods which were panicking. Would be nice if panics always got printed.

**Comment by elsirion** [comment] 2023-05-26 14:24
That's unexpected, I'd think it'd crash the entire state machine executor and log the panic when doing so. Should we catch panics from inside state machines and delete faulty ones after logging the error?

**Comment by justinmoon** [comment] 2023-05-29 16:24
Call: @dpc  says tokio swallows panics unless you join them or soemthing

**Comment by elsirion** [comment] 2023-07-31 10:52
This must have been fixed in the meantime, cannot reproduce. 

<details>
  <summary>Patch to reproduce</summary>

```patch
diff --git a/modules/fedimint-mint-client/src/oob.rs b/modules/fedimint-mint-client/src/oob.rs
index d91e22db6b..49ca0e7d2d 100644
--- a/modules/fedimint-mint-client/src/oob.rs
+++ b/modules/fedimint-mint-client/src/oob.rs
@@ -91,6 +91,7 @@ impl MintOOBStatesCreated {
         context: &MintClientContext,
         global_context: &DynGlobalClientContext,
     ) -> Vec<StateTransition<MintOOBStateMachine>> {
+        panic!("FOOOO");
         // TODO: pass refund contexts into state transitions
         let user_cancel_gc = global_context.clone();
         let timeout_cancel_gc = global_context.clone();
```
</details>

![2023-07-31-124823_5120x1440_scrot](https://github.com/fedimint/fedimint/assets/84478054/c9347d29-1239-45b8-aaf8-b92976bfa078)

**Closed by elsirion** 2023-07-31 10:52 UTC
