### ISSUE TITLE
Gateway channel force closures

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1018] opened 2022-11-29 22:32 UTC
I began running a gateway again (on aa18eb5c36f962f58e1396e8cc41cec9783528a4) and channels started force closing again shortly after the gateway experienced an error. The same happened at HCPP. I don't 100% know if it's related, but if feels fishy. Happy to provide more logs privately @okjodom.

```
… a whole bunch on API requests
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=1
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=3
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=0
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=1
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=2
Nov 29 10:24:25 bitcoin lightningd[526750]: INFO    plugin-ln_gateway: request; peer=3
Nov 29 10:24:25 bitcoin lightningd[526750]: **BROKEN** plugin-ln_gateway: htlc_accepted error Federation client operation error: LnClientError(ApiError(Timeout))\n\nCaused by:\n    0: Lightning client error: Mint API error: Timeout error awaiting outcome\n    1: Mint API error: Timeout error awaiting outcome
Nov 29 10:47:23 bitcoin lightningd[526750]: UNUSUAL [channelid]-chan#1409: Peer permanent failure in CHANNELD_NORMAL: Funding transaction spent
Nov 29 10:47:23 bitcoin lightningd[526750]: INFO    [channelid]-chan#1409: State changed from CHANNELD_NORMAL to AWAITING_UNILATERAL
Nov 29 10:47:23 bitcoin lightningd[526750]: INFO    [channelid]-chan#1409: State changed from AWAITING_UNILATERAL to FUNDING_SPEND_SEEN
Nov 29 10:47:23 bitcoin lightningd[526750]: INFO    [channelid]-chan#1409: State changed from FUNDING_SPEND_SEEN to ONCHAIN
```

**Comment by jkitman** [comment] 2023-04-21 11:37
Is this fixed?

**Comment by okjodom** [comment] 2023-04-21 14:39
I believe so.
We suspected the force closures were caused by forwarding HTLCs over the virtual LN hop created between gateway node and the mint. This was addressed by several changes, including:
- #1382
- Shift to the CLN extension which introduced better logic for [completing HTLC after processing](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/bin/cln_extension.rs#L241)

**Closed by okjodom** 2023-04-21 14:39 UTC
Labels: bug, lightning

**Comment by justinmoon** [comment] 2023-04-21 22:02
I've been able to run a pre-gatewayd gateway for a month without any channel closures so I think we can close for now, and have been running a gatewayd gateway for late week or two without any.
