### ISSUE TITLE
On start fedimint should check the bitcoin node

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1416] opened 2023-01-19 18:11 UTC
Maybe we could have

```
ModuleGen::check_env(/* the env vars we pass to modules*)
```

and call it on each module kind in `ModuleInitRegistry`

Then Wallet Module should try to make a `getblockcount`, check network and display this info, or print and error.

This would help a lot get a quick feedback even before setting up the federation.

**Comment by elsirion** [comment] 2023-01-20 03:20
Even better eventually: display if the BTC node is reachable in the setup UI and help people fix their `bitcoind`+`fedimintd` setup if it isn't.

**Comment by asifshiraz** [comment] 2023-02-05 11:10
What should the check_env function do. Validate that the FM_BITCOIND_RPC or FM_ELECTRUM_RPC is present?

**Comment by elsirion** [comment] 2023-02-06 04:04
> What should the check_env function do. Validate that the FM_BITCOIND_RPC or FM_ELECTRUM_RPC is present?

Not only a presence check of the variable, but also if we can e.g. fetch the block height and maybe even fee levels to also fix #1417. I.e. make sure that whatever BTC backend is indicated via env vars actually works.

**Comment by asifshiraz** [comment] 2023-02-11 14:00
A few questions on this.

Implementation:
Module registry init function return IServerModule, at which point all internal module configuration involving its dependency on bitcoin has already happened deep inside it. Instead of coming out of that setup, and then calling another function to check the setup (in ModuleGen trait), and then making sure its always called, how about we bundle the validation inside the init, and in this particular case, directly in Wallet::new_with_bitcoind, where we already do some validations like checking that the bitcoin network matches the consensus network. We can check to see we can fetch block height and fee rate.

Testing:
If we do the above, to test this, I would need a unit test on Wallet with a mock IBitcoindRpc that I could stub to fail on get_block_height and get_free-rate. But I noticed there isn't any mock library or unit tests existing to give me a pattern on that. Should I write an integration test using FakeBitcoinTest, but there too, I'll either need to duplicate it to fail its get_block_height methods, or else introducing our own manual stubbing inside this fake e.g. an vec that can be set by tests to customize behavior. (And also, is a separate FakeBitcoindRpc also there by design, or can these two be merged)

**Comment by dpc** [comment] 2023-02-12 03:55
I agree it's best to just do it somewhere in init.

I would not bother with testing it with a unit-test. Too much turning stuff inside out for something that should only print `info!("Bitcoind reachable. Current block height {height}H");` or `error!("Unable to reach bitcoind. Error: {error}");`

The whole point here is to give the operator quick feedback that wallet module is initialized and is able to do it's job.

**Closed** 2023-02-23 13:18 UTC
Labels: good first issue
