### ISSUE TITLE
Benchmark `find_by_prefix_sorted_descending`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6050] opened 2024-09-19 21:20 UTC
`BackupWriter::append` uses it, which is called every AlephBFT unit afaik. We noticed a performance regression (multiples of CPU usage) from 0.3 to 0.4 that is likely related to it (`perf` showed lots of time spent in that function).

**Comment by dpc** [comment] 2024-09-19 22:18
I have wrote a test against prod-like dataset and that `.find_by_prefix_sorted_descending` there takes on my machine (which has probably waay faster IO than whatever cloud instances) takes `duration_ms=3`. I have 2.5k alephbfts items in that collection.

Not terrible, but add some VPS networked IO slowdown, and it might be taking almost as much as the round time?

**Comment by dpc** [comment] 2024-09-19 22:39
Using `let iterator_mode: IteratorMode = rocksdb::IteratorMode::End;` all the time doesn't change anything.

**Comment by dpc** [comment] 2024-09-19 22:41
I have no other ideas. @m1sterc001guy any ideas?

**Comment by m1sterc001guy** [comment] 2024-09-20 14:24
`raw_find_by_prefix_sorted_descending` and `raw_find_by_prefix` are very similar, just the iter direction is reversed. Unless there's a bug in rocksdb I don't see anything obvious.

Dumb question, but `find_by_prefix_sorted_descending` does the actual decoding of the key/values into the structs. Did  we have any new large database entries in 0.4 that could be the culprit?

**Comment by dpc** [comment] 2024-09-20 15:51
I have confirmed that in our code we only ever see a single item, as this query is just trying to get the last item only. `raw_find_by_prefix` takes 0ms. So AFAICT `find_by_prefix_sorted_descending` is significantly slower on the Rocksdb level. The profiling I did shows all the time is spent in rocksdb code as well, with some MergingIterators and FindPrevPos items suggesting what's going on.

**Comment by dpc** [comment] 2024-09-20 15:51
Unless there are some magic arguments that we can pass / we missed / set wrong, we probably just need to accept that `find_by_prefix_sorted_descending` is just slowish, and we should avoid it.

**Comment by dpc** [comment] 2024-09-20 16:07
I wonder if iterating backwards might just not work well inherently due to data model. Rocksdb is ussing this SST, which I think are just sorted arrays, and maybe if the elements are stored inline, prefixed with length, but not suffixed with length, it might just not have a cheap way to iterate backwards, and needs to do a O(ln n) lookup every time it iterates? That would explain `FindPrevPos` being a big part of the profile we captured.

**Comment by m1sterc001guy** [comment] 2024-09-20 16:12
The length inlining making it slow would make sense. I'm not familiar with how rocksdb is doing the iteration, but some basic searches do seem to confirm that reverse iteration is slower:

> You can also process entries in reverse order. (Caveat: reverse iteration may be somewhat slower than forward iteration.)

https://github.com/facebook/rocksdb/wiki/basic-operations

**Comment by dpc** [comment] 2024-09-20 18:54
The immediate problem should be fixed by #6054 . And I also doubt there's much reason to spend  too much time on this.

**Comment by joschisan** [comment] 2024-09-20 20:25
Let’s not overreact here, especially with a new database entry for something completely theoretical. This was in a hot loop called 80 times a second.

**Comment by dpc** [comment] 2024-09-20 20:37
> Instead of a new db entry we could also use a watch channel to track it.

Each time I want cache something about the database state in memory, I'm contemplating weird atomicity and consistency corner cases. I have no problem with any working solution.

>  This was in a hot loop called 80 times a second.

Well, the worry is, these APIs could get called 80 times a second by a malicious client.

**Comment by elsirion** [comment] 2024-09-23 13:14
While we likely fixed that particular slowness, I don't really understand why it happened. I did a synthetic benchmark (#6069) and there's no obvious slowness. Some stuff left to test though (please comment any other expected sources of slowdown).

**Comment by dpc** [comment] 2024-09-25 21:50
Found it, by unrelated accident.

![image](https://github.com/user-attachments/assets/a66e6efa-c239-4390-b306-8f29a0b4b57a)


https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ

**Comment by dpc** [comment] 2024-09-30 17:22
Other than being ware that it's somewhat slower, I don't think there's much to do here, and I doubt anyone has time to dig into it. If I'm wrong please re-open.

**Closed by dpc** 2024-09-30 17:22 UTC
Labels: db, perf, alephbft
