### ISSUE TITLE
Crash recovery, rejoining and banned peers

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1318] opened 2023-01-13 21:36 UTC
In a recent deployment #1316 lead to a panic of one of the guardians.

The logs indicate that at least the network stack kept running since otherwise `systemd` typically prints a restart message. Secondly, it appears our peers banned us (not that this is a 3-of-3 federation for *#reasons* so only two peers banned us, but that should not matter). 

We need to:
1. Ensure the federation shuts down completely so that it can attempt to re-join in such a case
2. Figure out why that peer got banned. It seems like the epoch signature the previously failed peer contributed was for an earlier epoch.
3. Unban when peers wen a node restarts itself, so that a restart of an entire federation can quick-fix certain bugs (this would still require coordination, so would not hide the problem)

Furthermore, I'd like to simulate a failure of this kind where an epoch is lost and see if our current rejoin code could handle it gracefully.

## Logs

<details>
  <summary>Log of the failed guardian (charlie)</summary>

```
Jan 12 23:20:14 charlie fedimintd[32185]: - Epoch: 510 [PeerId(0), PeerId(1), PeerId(2)] -
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Transaction
Jan 12 23:20:14 charlie fedimintd[32185]:     Input: Lightning Contract f3dd1a942454997378c29814088d167470a45811ac636457a2f0ccd4ebf63730 with amount 40000000 msat
Jan 12 23:20:14 charlie fedimintd[32185]:     Output: Mint Coins 40000000 msat
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 1: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 1: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 2: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 2: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]: thread 'main' panicked at 'DB Error: Resource busy: ', /build/source/fedimint-server/src/consensus/mod.rs:302:36
Jan 12 23:20:14 charlie fedimintd[32185]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jan 12 23:20:16 charlie fedimintd[32185]: 2023-01-12T23:20:16.583495Z  WARN fedimint_server::net::peers: Could not send incoming connection to peer io task (possibly banned) peer=PeerId(1)
Jan 12 23:20:17 charlie fedimintd[32185]: 2023-01-12T23:20:17.518065Z  WARN fedimint_server::net::peers: Could not send incoming connection to peer io task (possibly banned) peer=PeerId(0)
Jan 12 23:20:17 charlie fedimintd[32185]: 2023-01-12T23:20:17.733970Z  WARN fedimint_server::net::peers: Could not send incoming connection to peer io task (possibly banned) peer=PeerId(1)
```  
</details>

<details>
  <summary>Log of the guardian that banned charlie after a restart of the entire federation</summary>

```
Jan 13 19:31:35 alpha fedimintd[42194]: 2023-01-13T19:31:35.372933Z  WARN fedimintd::encrypt: READ "/var/lib/fedimint/private.encrypt"
Jan 13 19:31:35 alpha fedimintd[42194]: 2023-01-13T19:31:35.831042Z  INFO fedimint_server: Starting consensus at epoch 511
Jan 13 19:31:39 alpha fedimintd[42194]: 2023-01-13T19:31:39.402843Z  INFO fedimint_server: Requested to run 1 epochs
Jan 13 19:31:39 alpha fedimintd[42194]: 2023-01-13T19:31:39.643349Z  INFO fedimint_server: Requested to run 1 epochs
Jan 13 19:37:13 alpha fedimintd[42194]: 2023-01-13T19:37:13.203674Z  INFO fedimint_server: Requested to run 1 epochs
Jan 13 19:37:15 alpha fedimintd[42194]: 2023-01-13T19:37:15.720688Z  INFO fedimint_server:
Jan 13 19:37:15 alpha fedimintd[42194]: - Epoch: 511 [PeerId(0), PeerId(1), PeerId(2)] -
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 7719000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Wallet PegOut 0.00001 BTC to bc1q0a9fl549yq7hfssw79shl35lwt8xnxrcsyegpx4s3l0dp6kdwh6spqzmgz
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 394c669d29798fe6fb47b7b8404a00ef6669cd837c2c241f63cbaae091a853db
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash 25634e5c06e5dcc72ebd7c6c86b58897cfeddec13171028c3aaae3e0f6e0b980
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash be7b2e8660b5ca7975ebe1805060ee67f2df28237ca402f39a2b1553273d3c7a
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash a8c9e11a3c4e075b59db53bcdde0e4c29539204791b2947ca0fe06db94905ddc
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash e04f685ba18dc116eca27844f3c56fb9d1a4935a107581ac8bab1d52bbcaf5a8
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 41000000 msat with hash 97749cd205f0e7cb53e52f43b3b5392abf37704b73d978e89bd60b6306958d66
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 16384 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN Outgoing Contract for 10100 msat hash 7858417ffe7c55f2c623ae8ab2d5c0b0d904426e783c9d76b4f2f6d0ac33b0d5
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 6284 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 3af94a4282cbb2959ae085a59ea23e829bf439c339a655ab660ce8375172bafe
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash cbd3fb7b4c671527eea902feed137628f0f7f5faa7d7cba4d981a65bc01e2f76
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 0df7361b1fe2a922d4ec4f8d40f7f1b63429e4b583cef308d6deb966e9b05d58
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Lightning Contract 417072bf6a9bd8a38d4dcf6b43c8c838897207ceac92bb382f00c5039b06cae4 with amount 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash b48ed1b37b2351bc41f4a547acd7e2a196a5d3a2938b1e6ec0ab9d31f08d3217
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash 035dc6ec9a707933db1cade69e5db7bb5fd0576df42ee491649d6a9d6d7ad690
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Module CI: module=0 ci=Wallet Block Height 771781
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Module CI: module=1 ci=Mint Blind Signature Shares worth 40000000 msat for 45272fc158d74f21753bb2d171b03fec422f66a5b8be3c9c977749c1b39b067d:0
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 0: Outcome Signature
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 7719000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Wallet PegOut 0.00001 BTC to bc1q0a9fl549yq7hfssw79shl35lwt8xnxrcsyegpx4s3l0dp6kdwh6spqzmgz
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 394c669d29798fe6fb47b7b8404a00ef6669cd837c2c241f63cbaae091a853db
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash 25634e5c06e5dcc72ebd7c6c86b58897cfeddec13171028c3aaae3e0f6e0b980
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash be7b2e8660b5ca7975ebe1805060ee67f2df28237ca402f39a2b1553273d3c7a
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash a8c9e11a3c4e075b59db53bcdde0e4c29539204791b2947ca0fe06db94905ddc
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash e04f685ba18dc116eca27844f3c56fb9d1a4935a107581ac8bab1d52bbcaf5a8
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 41000000 msat with hash 97749cd205f0e7cb53e52f43b3b5392abf37704b73d978e89bd60b6306958d66
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 16384 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN Outgoing Contract for 10100 msat hash 7858417ffe7c55f2c623ae8ab2d5c0b0d904426e783c9d76b4f2f6d0ac33b0d5
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 6284 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 3af94a4282cbb2959ae085a59ea23e829bf439c339a655ab660ce8375172bafe
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash cbd3fb7b4c671527eea902feed137628f0f7f5faa7d7cba4d981a65bc01e2f76
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 0df7361b1fe2a922d4ec4f8d40f7f1b63429e4b583cef308d6deb966e9b05d58
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Lightning Contract 417072bf6a9bd8a38d4dcf6b43c8c838897207ceac92bb382f00c5039b06cae4 with amount 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash b48ed1b37b2351bc41f4a547acd7e2a196a5d3a2938b1e6ec0ab9d31f08d3217
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash 035dc6ec9a707933db1cade69e5db7bb5fd0576df42ee491649d6a9d6d7ad690
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash c183e9203a7c55ec2962bea8b63dc4c54a681ff8f2c7a2ff8f52ffaf7150e0a8
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Module CI: module=0 ci=Wallet Block Height 771781
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Module CI: module=1 ci=Mint Blind Signature Shares worth 40000000 msat for 45272fc158d74f21753bb2d171b03fec422f66a5b8be3c9c977749c1b39b067d:0
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 1: Outcome Signature
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 7719000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Wallet PegOut 0.00001 BTC to bc1q0a9fl549yq7hfssw79shl35lwt8xnxrcsyegpx4s3l0dp6kdwh6spqzmgz
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 394c669d29798fe6fb47b7b8404a00ef6669cd837c2c241f63cbaae091a853db
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash 25634e5c06e5dcc72ebd7c6c86b58897cfeddec13171028c3aaae3e0f6e0b980
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash be7b2e8660b5ca7975ebe1805060ee67f2df28237ca402f39a2b1553273d3c7a
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash a8c9e11a3c4e075b59db53bcdde0e4c29539204791b2947ca0fe06db94905ddc
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash e04f685ba18dc116eca27844f3c56fb9d1a4935a107581ac8bab1d52bbcaf5a8
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 41000000 msat with hash 97749cd205f0e7cb53e52f43b3b5392abf37704b73d978e89bd60b6306958d66
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Mint Coins 16384 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN Outgoing Contract for 10100 msat hash 7858417ffe7c55f2c623ae8ab2d5c0b0d904426e783c9d76b4f2f6d0ac33b0d5
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 6284 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 3af94a4282cbb2959ae085a59ea23e829bf439c339a655ab660ce8375172bafe
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash cbd3fb7b4c671527eea902feed137628f0f7f5faa7d7cba4d981a65bc01e2f76
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 10000 msat with hash 0df7361b1fe2a922d4ec4f8d40f7f1b63429e4b583cef308d6deb966e9b05d58
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Input: Lightning Contract 417072bf6a9bd8a38d4dcf6b43c8c838897207ceac92bb382f00c5039b06cae4 with amount 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 40400000 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash b48ed1b37b2351bc41f4a547acd7e2a196a5d3a2938b1e6ec0ab9d31f08d3217
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash 035dc6ec9a707933db1cade69e5db7bb5fd0576df42ee491649d6a9d6d7ad690
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 40000000 msat with hash c183e9203a7c55ec2962bea8b63dc4c54a681ff8f2c7a2ff8f52ffaf7150e0a8
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Module CI: module=0 ci=Wallet Block Height 771781
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Module CI: module=1 ci=Mint Blind Signature Shares worth 40000000 msat for 45272fc158d74f21753bb2d171b03fec422f66a5b8be3c9c977749c1b39b067d:0
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Outcome Signature
Jan 13 19:37:15 alpha fedimintd[42194]: 2023-01-13T19:37:15.722928Z  INFO process_consensus_outcome{epoch=511}: fedimint_wallet: New consensus height, syncing up new_height=771781 block_to_go=131
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.284020Z  INFO process_consensus_outcome{epoch=511}:Processing transaction: fedimint_wallet: Creating peg-out tx inputs=1 input_sats=2000000 peg_out_sats=1000 fees_sats=6719 fee_rate=7593 change_sats=1992281
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.284733Z  INFO process_consensus_outcome{epoch=511}:Processing transaction: fedimint_wallet: Creating peg-out tx txid=eea91bd2cbf332c80232fc0abe52fc1b1478e0f3a6307eafd4fb4673a829458a
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.285310Z  INFO process_consensus_outcome{epoch=511}:Processing transaction: fedimint_wallet: Creating peg-out tx inputs=1 input_sats=2000000 peg_out_sats=1000 fees_sats=6719 fee_rate=7593 change_sats=1992281
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.285409Z  INFO process_consensus_outcome{epoch=511}:Processing transaction: fedimint_wallet: Creating peg-out tx txid=eea91bd2cbf332c80232fc0abe52fc1b1478e0f3a6307eafd4fb4673a829458a
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.285797Z  INFO process_consensus_outcome{epoch=511}:Processing transaction: fedimint_wallet: Signing peg out txid=eea91bd2cbf332c80232fc0abe52fc1b1478e0f3a6307eafd4fb4673a829458a
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.559851Z ERROR process_consensus_outcome{epoch=511}: fedimint_mint: Dropping PeerId(2) for InvalidSignature
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.560610Z  WARN process_consensus_outcome{epoch=511}: fedimint_mint: Could not combine shares error=Too few valid shares, only 2 of 3 (required minimum 3) provided shares were valid
Jan 13 19:37:16 alpha fedimintd[42194]: 2023-01-13T19:37:16.785895Z  WARN fedimint_server::net::peers: Peer 2 banned.
Jan 13 19:37:20 alpha fedimintd[42194]: 2023-01-13T19:37:20.710982Z  WARN fedimint_server::net::peers: Could not send incoming connection to peer io task (possibly banned) peer=PeerId(2)
Jan 13 19:37:23 alpha fedimintd[42194]: 2023-01-13T19:37:23.976169Z  WARN fedimint_server::net::peers: Could not send incoming connection to peer io task (possibly banned) peer=PeerId(2)
```

</details>

**Comment by dpc** [comment] 2023-01-13 22:28
> Figure out why that peer got banned. It seems like the epoch signature the previously failed peer contributed was for an earlier epoch.

For some context we discussed in a chat outside github:

As things are currently, the fedimintd consensus code will send messages that have side effects for the purpose of the consensus, while still not committed the corresponding state changes to the database.

This means that in case of a crash/shutdown before the database transaction was committed, the peer could have committed to stuff that it now forgot about, and e.g. send conflicting messages.

Typically such problems would be prevented by using "an outbox pattern" - writing out all the side-effects planed to the database first, along with all the state transitions, then committing the tx, and only then executing the side-effects then deleting them. Such a mechanism guarantee that the code will deliver every message at least once or zero times.

In our case the additional latency might not be worth pursuing this approach, but we either should be more lenient on the peers with temporary post-crash amnesia, or figure out other ways to make such crashes harmless.

One approach would be to simply ignore duplicated messages from the peer and responding with 'go home you're drunk'. If a peer collects (required_threshold - 1 /* for honest self */) to their first consensus messages they should resync with the consensus).

Another would be to ignore, but not ban duplicate messages that are exactly the same as previous one, and try to make the logic deterministic (including rngs). This might be much harder, especially in the presence of 3rd party modules.

Take all the above with a grain of salt. It was just a quick and short conversation.

**Comment by dpc** [comment] 2023-01-13 22:39
> Another would be to ignore, but not ban duplicate messages that are exactly the same as previous one, and try to make the logic deterministic (including rngs). This might be much harder, especially in the presence of 3rd party modules.


Actually this might not be enough, because the problem is that the peer already committed to something, that they have now forgot.

BUT! If we make peers store the previous messages of other peers temporarily, then they can respond with a previous commitment, and since all commitments are probably signed, the confused peer can verify: "oh, it seems I really did said that before I blacked out" and use that instead of the confused commitment they were trying to make.

The peers would only need to store the first received message from each peer, for as long as the consensus on a given round was not reached.

If the consensus was reached, it does not longer matter what the confused peer said, as they can sync from the consensus history.

Also - to avoid a problem of different peers remembering different versions of things, on start a peer should make one round of queries "hey, did I said anything before I passed out" to each other peer, and wait until they receive at least `required_threshold - 1 /* for self */` responses "no, you did not".

**Comment by dpc** [comment] 2023-01-13 23:21
I was joking on Discord:

> Looks like we have just made up our own variation of hbbft and I call it "heavy drinking honey badger byzantine fault tolerant" consensus. It's a version of hbbft where the badgers are having a party, and they sometimes black out just to wake up later and forgetting what they just committed to. In cases where badgers are Slavic or Irish, and they can drink a lot without passing out too often, it's a lower latency version hbbft, as the badgers don't have to write down everything they are about to say, in case they pass out. It might require more thought and research. Maybe even field testing.  

But after thinking about it in the shower, it occurred to me this is very accurate.

I have not confirmed with the original paper, but I bet that originally the authors assumed that peers in HBBFT can not loose memory w.r.t their commitments. It's an easy assumption to make, very reasonable, and I don't think the authors were concerned with real life performance aspects of the implementation.

Therefore, absent outbox pattern what we are implementing is not exactly original HBBFT.

What happened here is that the 3-of-3 federation stopped mid-epoch, and the crashed peer could not sync with the federation, because there were no more epochs to sync with. And the rest of the members couldn't make progress because they didn't have enough non-confused peers.

So everything got stuck, and the peer got banned for doing wrong things.

And I do think that by:

* storing (persisting) previous responses from other peers until the epoch is complete, before acting on them (sending any own commitments, or making changes in the db),
* on start asking for any existing commitments made,

fixes the problem without introducing extra serial db latency of an outbox pattern (the peers can store the past commitments in the same time as they collect other responses, and doing any heavy math, etc. just no side-effects).

However, I think it makes assumptions theoretical assumptions about network delivery order, etc. In theory an evil peer could conceal previous commitment, let the confused peer gather negative responses from other peers, then submit the previous commitment causing the previous peer to get banned after all.

In an real deployment, I don't think this is very practical attack, as the evil peer would have to:

* receive a message first and the only, as the peer crashes before delivering the message to any good peer,
* have the federation consensus stop because of the crashing peer.

It is possible, that peers would not have to *persist* commitments of other peers and only keep them in memory but that has a corner cases of "what if enough peers blacked out (or pretended to black out) at the same time, leaving the few honest peers out of consensus and banned for insisting on the already started round". This however can be fixed/mitigated by just broadcasting all the messages that were already commited to in the given (unfiished) epoch, so everyone self-heal themselves.

**Comment by elsirion** [comment] 2023-01-14 16:27
From call with @jkitman: we should process a consensus outcome in one big tx now that we have proper DB tx.

**Comment by dpc** [comment] 2023-02-27 18:04
@joschisan

**Comment by jkitman** [comment] 2023-04-26 11:31
Going to close this I think we have fixed the original cause.

**Closed by jkitman** 2023-04-26 11:31 UTC
Labels: bug, consensus
