### ISSUE TITLE
Cancelled LN payment update stream doesn't yield `Cancelled` state

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4014] opened 2024-01-05 13:39 UTC
See #4001

Repro (gets stuck):

```rust
#[tokio::test(flavor = "multi_thread")]
async fn gateway_cancels_payment() -> anyhow::Result<()> {
    let fixtures = fixtures();
    let fed = fixtures.new_fed().await;
    let client = fed.new_client().await;
    let gw = gateway(&fixtures, &fed).await;
    let dummy_module = client.get_first_module::<DummyClientModule>();

    // Print money for client
    let (op, outpoint) = dummy_module.print_money(sats(1000)).await?;
    client.await_primary_module_output(op, outpoint).await?;

    let cln = fixtures.cln().await;
    let invoice = Bolt11Invoice::from_str("lnbcrt420n1pje07kcdqqpp5vjadfxk9sxar4030cdh3ws4n9rfc2r6gzsrhrrysnc2ax75zfa7ssp53jaxxultl94h4an04a2rgv76xlgt3pjgy4txnd8h8mg8pdhumtlq9qrsgqcqpjnp4qwljl52cc7vnn76dmaau8qptly6q2uh3rl8d0gdn047wxxerf799yxqyz5vqrzjqt5a8fp65nlccjnyzhtfj82dw20pshv9wxlwt2j0u69snyypgpqvcqqqqqqqqqqqqyqqqqqqqqqqqqqqrcr9yqd332tteyjmz53r7k9a3yr86gmfgwdzxrv05h8mhkf0tpwz6d7j4sqqqwqqqqqgqqyqqqqlgqqqqqqgq2qpwn5ay82j0lrz2vs2adxgaf4efuxzas4cmaed2flngkzvss9qypnqqqqqqqqqqqqqsqqqqqqqqqqqqqq0qtuj76w6vuuxka7wg4ve357r8pdgh0msxpj9f0kqypc4k7g03uyl9v6sceh4hsdrv40pw3z8l4vz8vvz70zy3uyn5xys96c6clw6ksaqq5eax9q").expect("Valid invoice");

    let OutgoingLightningPayment {
        payment_type,
        contract_id: _,
        fee: _,
    } = pay_invoice(&client, invoice.clone()).await?;
    match payment_type {
        PayType::Lightning(operation_id) => {
            let mut sub = client
                .get_first_module::<LightningClientModule>()
                .subscribe_ln_pay(operation_id)
                .await?
                .into_stream();

            assert_eq!(sub.ok().await?, LnPayState::Created);
            error!("Created");
            assert_eq!(sub.ok().await?, LnPayState::Funded);
            error!("Funded");
            assert_matches!(sub.ok().await?, LnPayState::Success { .. });
            error!("Success");
        }
        _ => panic!("Expected lightning payment!"),
    }

    Ok(())
}
```

**Comment by m1sterc001guy** [comment] 2024-01-09 19:03
From my investigation it does look like the `Canceled` state is yield, but for some reason the Lightning client state machine is not able to transition to the `Refundable` state:

```
2024-01-09T18:57:43.830291Z ERROR state_machine_transition{operation_id=46df16d50fda66dd5b905e2f696f92b926219ee8d35a6610046adef6ba28eb22}: fedimint_client::sm::notifier: Could not send state transition notification, the client may misbehave e=SendError(LightningPay(LightningPayStateMachine { common: LightningPayCommon { operation_id: OperationId(46df16d50fda66dd5b905e2f696f92b926219ee8d35a6610046adef6ba28eb22), federation_id: FederationId(aecdf60555556974432450d8a588c251c25433e7db08bbf67d0b8d1f3bbcc4a0), contract: OutgoingContractData { recovery_key: KeyPair(#d5c55a064fc1859c), contract_account: OutgoingContractAccount { amount: Amount { msats: 42000 }, contract: OutgoingContract { hash: 64bad49ac581ba3abe2fc36f1742b328d3850f481407718c909e15d37a824f7d, gateway_key: PublicKey(d2e16676eb23d28053a4e5eee3ad75ae9523e552a6c53ec5c8375e3f30d5735d6116b59b899580acfa3685bff29db976a1c48a4d6feca81c4f57e8aeb6645740), timelock: 500, user_key: PublicKey(32cc69d650e18759efa82c70a4793e60c9708b616af665d0ac362fb559bb3154d7b14c6a16b80c3ca51cb81ba9ca7aa7401927a40fc385a95e19220c2b688d8e), cancelled: false } } }, gateway_fee: Amount { msats: 0 }, preimage_auth: 7d3a9d7d22fdec509dadff65c17a4b26825b50c1faf24aac93fb0a5c5781973f, invoice: Bolt11Invoice { signed_invoice: SignedRawBolt11Invoice { raw_invoice: RawBolt11Invoice { hrp: RawHrp { currency: Regtest, raw_amount: Some(420), si_prefix: Some(Nano) }, data: RawDataPart { timestamp: PositiveTimestamp(1704458968s), tagged_fields: [KnownSemantics(Description(Description(""))), KnownSemantics(PaymentHash(Sha256(64bad49ac581ba3abe2fc36f1742b328d3850f481407718c909e15d37a824f7d))), KnownSemantics(PaymentSecret(PaymentSecret([140, 186, 99, 115, 235, 249, 107, 122, 246, 111, 175, 84, 52, 51, 218, 55, 208, 184, 134, 72, 37, 86, 105, 180, 247, 62, 208, 112, 182, 252, 218, 254]))), KnownSemantics(Features([0, 65])), KnownSemantics(MinFinalCltvExpiryDelta(MinFinalCltvExpiryDelta(18))), KnownSemantics(PayeePubKey(PayeePubKey(PublicKey(528a4f231be37c7db3a1d7ce1ff1720534f92b80c37bdf4dfb3999c758d12fbfdfc8725f572680985c1f65161e523b5afe6037aec0c30604a2db68df523de1e3)))), KnownSemantics(ExpiryTime(ExpiryTime(86400s))), KnownSemantics(PrivateRoute(PrivateRoute(RouteHint([RouteHintHop { src_node_id: PublicKey(cc40408190098be64faae5be71855d189e724d1d99d615644a8cffa43aa4d3e9e8eeb3011822f81c56e304f580c3af31279ef849b89bd3863ef32bfacf1be0f0), short_channel_id: 1, fees: RoutingFees { base_msat: 0, proportional_millionths: 0 }, cltv_expiry_delta: 30, htlc_minimum_msat: None, htlc_maximum_msat: None }])))), KnownSemantics(PrivateRoute(PrivateRoute(RouteHint([RouteHintHop { src_node_id: PublicKey(58a56f5ab8b05eb2779f4b1f1b463487d246fa0c127bb17e442ab624792d1563f9f7bd5aa1724720630ec298b1c47c4baeceaee6963a9d0543f98272f49397ec), short_channel_id: 123145302376449, fees: RoutingFees { base_msat: 1000, proportional_millionths: 1 }, cltv_expiry_delta: 80, htlc_minimum_msat: None, htlc_maximum_msat: None }, RouteHintHop { src_node_id: PublicKey(cc40408190098be64faae5be71855d189e724d1d99d615644a8cffa43aa4d3e9e8eeb3011822f81c56e304f580c3af31279ef849b89bd3863ef32bfacf1be0f0), short_channel_id: 1, fees: RoutingFees { base_msat: 0, proportional_millionths: 0 }, cltv_expiry_delta: 30, htlc_minimum_msat: None, htlc_maximum_msat: None }]))))] } }, hash: [83, 158, 43, 112, 205, 29, 239, 99, 61, 205, 136, 51, 51, 242, 223, 98, 151, 32, 83, 169, 116, 32, 148, 153, 191, 115, 81, 245, 251, 79, 197, 237], signature: Bolt11InvoiceSignature(RecoverableSignature(5f25ed3b4ce70d6ef9c8ab331a78670b5177ee060c8a97d8040e2b6f21f1e13e566a18cdeb78346cabc2e888ffab0476305e78891e127431205d6358fbb5687400)) } } }, state: Refundable(LightningPayRefundable { contract_id: 02d359bd4462c9e295f8e53f77a6b3b19bacf147f1c63bc42edb70fc5fb9bdad, block_timelock: 500, error: GatewayInternalError { error_code: Some(400), error_message: "Error while paying lightning invoice. Outgoing contract will be refunded." } }) }))
```

**Comment by m1sterc001guy** [comment] 2024-01-09 20:05
Actually, disregard the previous comment, I think that error message is benign.

I haven't been able to reproduce `Cancelled` not being yielded. I modified your test slightly and got it to pass (all I changed was waiting for the proper states at the end):

```
#[tokio::test(flavor = "multi_thread")]
async fn gateway_cancels_payment() -> anyhow::Result<()> {
    let fixtures = fixtures();
    let fed = fixtures.new_fed().await;
    let client = fed.new_client().await;
    let gw = gateway(&fixtures, &fed).await;
    let dummy_module = client.get_first_module::<DummyClientModule>();

    // Print money for client
    let (op, outpoint) = dummy_module.print_money(sats(1000)).await?;
    client.await_primary_module_output(op, outpoint).await?;

    let cln = fixtures.cln().await;
    let invoice = Bolt11Invoice::from_str("lnbcrt420n1pje07kcdqqpp5vjadfxk9sxar4030cdh3ws4n9rfc2r6gzsrhrrysnc2ax75zfa7ssp53jaxxultl94h4an04a2rgv76xlgt3pjgy4txnd8h8mg8pdhumtlq9qrsgqcqpjnp4qwljl52cc7vnn76dmaau8qptly6q2uh3rl8d0gdn047wxxerf799yxqyz5vqrzjqt5a8fp65nlccjnyzhtfj82dw20pshv9wxlwt2j0u69snyypgpqvcqqqqqqqqqqqqyqqqqqqqqqqqqqqrcr9yqd332tteyjmz53r7k9a3yr86gmfgwdzxrv05h8mhkf0tpwz6d7j4sqqqwqqqqqgqqyqqqqlgqqqqqqgq2qpwn5ay82j0lrz2vs2adxgaf4efuxzas4cmaed2flngkzvss9qypnqqqqqqqqqqqqqsqqqqqqqqqqqqqq0qtuj76w6vuuxka7wg4ve357r8pdgh0msxpj9f0kqypc4k7g03uyl9v6sceh4hsdrv40pw3z8l4vz8vvz70zy3uyn5xys96c6clw6ksaqq5eax9q").expect("Valid invoice");

    let OutgoingLightningPayment {
        payment_type,
        contract_id: _,
        fee: _,
    } = pay_invoice(&client, invoice.clone()).await?;
    match payment_type {
        PayType::Lightning(operation_id) => {
            let mut sub = client
                .get_first_module::<LightningClientModule>()
                .subscribe_ln_pay(operation_id)
                .await?
                .into_stream();

            assert_eq!(sub.ok().await?, LnPayState::Created);
            error!("Created");
            assert_eq!(sub.ok().await?, LnPayState::Funded);
            error!("Funded");
            assert_matches!(sub.ok().await?, LnPayState::WaitingForRefund { .. });
            error!("WaitingForRefund");
            assert_matches!(sub.ok().await?, LnPayState::Refunded { .. });
            error!("Refunded");
        }
        _ => panic!("Expected lightning payment!"),
    }

    Ok(())
}
```

Some things that I noticed:
1. The client retries to contact the gateway every second on _any_ failure, for a full 30 seconds before checking if the contract has been cancelled. IMO this is wasteful and is polluting the gateway's logs making it difficult to debug. We should probably only retry to contact the gateway if we get a 400 error, and not if the gateway responded with an error indicating the payment failed.
2.  I think the `Refundable` state is redundant. I think after a contract is funded, we should wait one one of three futures:

 - Payment was made successfully
 - Contract has been cancelled
 - Timelock has expired.

This would eliminate the need for the 30 second timeout altogether. With this refactor, we'll probably still want to re-try the payment when the gateway returns 400/500 status code, but the retry delay for 500 status codes should be much higher (since it's very unlikely that if the gateway responded with an error before, that it will work on a retry). Retrying on 400 error codes offers some robustness against network failures.

**Comment by m1sterc001guy** [comment] 2024-10-07 22:33
Fixed with https://github.com/fedimint/fedimint/pull/4024

**Closed by m1sterc001guy** 2024-10-07 22:33 UTC
Labels: bug, lightning, client, backport releases/v0.2
