### ISSUE TITLE
Fedimint tonic_lnd tracking issue

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#4029] opened 2024-01-11 10:36 UTC
Tracking issue for new release of https://github.com/fedimint/tonic_lnd/pull/18
With tls cert sorting for gateways to connect to remote nodes on different boxes (e.g. voltage)

**Comment by justinmoon** [comment] 2024-01-11 23:10
I think this is a duplicate of https://github.com/fedimint/fedimint/issues/3915

**Closed by justinmoon** 2024-01-11 23:10 UTC
